# -*- coding: utf-8 -*-
# *** Spyder Python Console History Log ***

## ---(Tue May 24 12:23:47 2022)---
runfile('C:/Users/hyunj/.spyder-py3/ImageCosineSimilarity.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(3, 'C:/Users/hyunj/.spyder-py3/ImageCosineSimilarity.py')
debugfile('C:/Users/hyunj/.spyder-py3/ImageCosineSimilarity.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(3, 'C:/Users/hyunj/.spyder-py3/ImageCosineSimilarity.py')
runcell(4, 'C:/Users/hyunj/.spyder-py3/ImageCosineSimilarity.py')
runcell(5, 'C:/Users/hyunj/.spyder-py3/ImageCosineSimilarity.py')
runcell(0, 'C:/Users/hyunj/.spyder-py3/ImageCosineSimilarity.py')

## ---(Wed May 25 17:54:27 2022)---
runcell(11, 'C:/Users/hyunj/.spyder-py3/MSE.py')
runcell(0, 'C:/Users/hyunj/.spyder-py3/MSE.py')
runfile('C:/Users/hyunj/.spyder-py3/MSE.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(11, 'C:/Users/hyunj/.spyder-py3/MSE.py')

## ---(Wed May 25 23:53:56 2022)---
runcell(0, 'C:/Users/hyunj/untitled0.py')
runcell(0, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runfile('C:/Users/hyunj/.spyder-py3/MYWAY.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(0, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runfile('C:/Users/hyunj/.spyder-py3/MYWAY.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(0, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runcell(1, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runfile('C:/Users/hyunj/.spyder-py3/MYWAY.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(0, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runfile('C:/Users/hyunj/.spyder-py3/MYWAY.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(0, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runfile('C:/Users/hyunj/.spyder-py3/MYWAY.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(0, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runcell(1, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runcell(2, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runfile('C:/Users/hyunj/.spyder-py3/MYWAY.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(1, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runfile('C:/Users/hyunj/.spyder-py3/MYWAY.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(3, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runfile('C:/Users/hyunj/.spyder-py3/MYWAY.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(3, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runfile('C:/Users/hyunj/.spyder-py3/MYWAY.py', wdir='C:/Users/hyunj/.spyder-py3')

## ---(Thu May 26 15:42:30 2022)---
runfile('C:/Users/hyunj/.spyder-py3/MYWAY.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(4, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runfile('C:/Users/hyunj/.spyder-py3/MYWAY.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(4, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runfile('C:/Users/hyunj/.spyder-py3/MYWAY.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(0, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runfile('C:/Users/hyunj/.spyder-py3/MYWAY.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(1, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runcell(0, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runcell(4, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runcell(0, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')
runcell(4, 'C:/Users/hyunj/.spyder-py3/MYWAY.py')

## ---(Fri May 27 16:46:02 2022)---
runcell(1, 'C:/Users/hyunj/.spyder-py3/RNN.py')
runfile('C:/Users/hyunj/.spyder-py3/RNN.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(1, 'C:/Users/hyunj/.spyder-py3/RNN.py')
runcell(2, 'C:/Users/hyunj/.spyder-py3/RNN.py')
runfile('C:/Users/hyunj/.spyder-py3/RNN.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(2, 'C:/Users/hyunj/.spyder-py3/RNN.py')
runfile('C:/Users/hyunj/.spyder-py3/RNN.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(2, 'C:/Users/hyunj/.spyder-py3/RNN.py')
runfile('C:/Users/hyunj/.spyder-py3/RNN.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(1, 'C:/Users/hyunj/.spyder-py3/RNN.py')
runfile('C:/Users/hyunj/.spyder-py3/RNN.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(3, 'C:/Users/hyunj/.spyder-py3/RNN.py')
runfile('C:/Users/hyunj/.spyder-py3/RNN.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(1, 'C:/Users/hyunj/.spyder-py3/RNN.py')
runfile('C:/Users/hyunj/.spyder-py3/RNN.py', wdir='C:/Users/hyunj/.spyder-py3')

## ---(Fri May 27 23:15:26 2022)---
runfile('C:/Users/hyunj/.spyder-py3/RNN.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(4, 'C:/Users/hyunj/.spyder-py3/RNN.py')
runcell(5, 'C:/Users/hyunj/.spyder-py3/RNN.py')
runfile('C:/Users/hyunj/.spyder-py3/RNN.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(3, 'C:/Users/hyunj/.spyder-py3/RNN.py')
runfile('C:/Users/hyunj/.spyder-py3/RNN.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(3, 'C:/Users/hyunj/.spyder-py3/RNN.py')
runfile('C:/Users/hyunj/.spyder-py3/RNN.py', wdir='C:/Users/hyunj/.spyder-py3')

## ---(Sat May 28 15:44:58 2022)---
runfile('C:/Users/hyunj/.spyder-py3/RNN.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(4, 'C:/Users/hyunj/.spyder-py3/RNN.py')
runfile('C:/Users/hyunj/.spyder-py3/RNN.py', wdir='C:/Users/hyunj/.spyder-py3')
runcell(4, 'C:/Users/hyunj/.spyder-py3/RNN.py')
runfile('C:/Users/hyunj/.spyder-py3/RNN.py', wdir='C:/Users/hyunj/.spyder-py3')